[17기 허정윤] Add: (cart/views.py) OrderDetailView 클래스 추가 - 청구 정보, 배송 정보 저장
wecode-bootcamp-korea/17-1st-Dienstag-backend pull request #10
Opened 2021-02-23 11:47 UTC by banana1019

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Add: (cart/views.py) OrderDetailView 클래스 추가 - 청구 정보, 배송 정보 저장
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- OrderDetailView 클래스를 user/views.py에서 cart/views.py로 옮겼습니다~~

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- .

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-23 16:46 UTC, Kang-kyunghun requested changes

2021-02-23 16:46 UTC, Kang-kyunghun commented on cart/views.py
> +                billing_last_name=billing_last_name,
```suggestion
                user_id            = user.id,
                billing_country    = data['billing_country'],
                billing_first_name = data['billing_first_name'],
                billing_last_name  = data['billing_last_name'],
```
1. =을 기준으로 라인 맞춰 주세요.
2. 프론트에서 받아오는 데이터를 변수에 담지 말고 바로 그냥 사용하셔도 될 것 같습니다. 이번 같은 경우는 변수에 담아서 여러번 사용하지 않고, 바로 데이터를 저장하기 때문에 변수에 따로 저장하지 않아도 될 것 같아요.

2021-02-23 20:36 UTC, banana1019 commented on cart/views.py
> +                billing_last_name=billing_last_name,
위코드 코딩 컨벤션 반영하였습니다~
데이터 변수에 담은 부분 삭제했습니다~~ 감사합니다!

2021-02-24 03:01 UTC, Kang-kyunghun commented
LGTM~~~!!!

2021-02-24 03:01 UTC, merged