CREATE: Cart app
wecode-bootcamp-korea/17-1st-Dienstag-backend pull request #2
Opened 2021-02-17 07:37 UTC by markkimjr

2021-02-17 11:54 UTC, Kang-kyunghun requested changes
수정 사항과 다음 아래 사항 확인해 주세요.

- 전체적을 max_length 한 번 확인해 주세요.

2021-02-17 11:54 UTC, Kang-kyunghun commented on voucher/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2)
가격을 DecimalField로 하신 것은 정말 잘 하셨습니다. 그럼 현재 설정 하신 max_digits로 얼마까지 표현 할 수 있을까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on user/models.py
> +    username     = models.CharField(max_length=100, unique=True)
username이 똑같은 사람이 있을 수 있지 않을까요? 그리고, username라는 필드명보다는 name으로 바꾸셔도 될 것 같습니다. 테이블의 이름이 user_information이므로 name 만으로도 회원의 이름을 나타내는 필드라는 것을 알 수 있습니다.

2021-02-17 11:54 UTC, Kang-kyunghun commented on user/models.py
> +    user         = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='user_information')
null = True을 사용한 이유를 알 수 있을까요? null = True을 사용하게 되면 어떤 문제가 있을까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on cart/models.py
> +
1. 장바구니에서 어떤 유저의 장바구니인지 어떻게 알 수 있을까요?
2. 모든 foreignkey들의 옵션이 on_delete=models.SET_NULL을 사용하셨는데, SET_NULL을 역할을 알고 계신가요? 다른 옵션들은 무엇들이 있을까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on cart/models.py
> +    billing_last_name           = models.CharField(max_length=45)
대부분의 max_legth=45로 되어 있습니다. 해당 필드의 길이로 정말 충분한 길이 일까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +
테이블 이름 추가 해주시면 좋을 것 같습니다.

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    video    = models.URLField()
URLField도 max_length를 지정해 주는 것이 좋습니다.

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    image_url = models.URLField()
위쪽과 같이 max_length 추가해 주세요.

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    bag_type = models.ForeignKey('BagType', on_delete=models.SET_NULL, null=True, related_name='bag_models')
null = True을 사용 했을 때 어떤 문제가 있을까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    bag_model    = models.ForeignKey('BagModel', on_delete=models.SET_NULL, null=True, related_name='products')
null = True을 사용 했을 때 어떤 문제가 있을까요?

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    color_name    = models.CharField(max_length=45)
테이블 이름에서 이미 color의 정보 나타내고 있기 때문에 color_name이라는 필드명보다는 name으로 수정하는 것이 좋습니다.

2021-02-17 11:54 UTC, Kang-kyunghun commented on product/models.py
> +    size_name    = models.CharField(max_length=45)
테이블 이름에서 이미 size의 정보 나타내고 있기 때문에 size_name이라는 필드명보다는 name으로 수정하는 것이 좋습니다.

2021-02-17 12:50 UTC, markkimjr commented on voucher/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2)
15로 수정했습니다~~

2021-02-17 12:52 UTC, markkimjr commented on user/models.py
> +    username     = models.CharField(max_length=100, unique=True)
실제 사람 이름이 아니라 login id를 의미해서 username이라는 필드명을 사용했습니다~~

2021-02-17 12:55 UTC, markkimjr commented on user/models.py
> +    user         = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='user_information')
on_delete=models.SET_NULL이여서 null=true를 입렸했었는데, 수정하였습니다.

2021-02-18 01:53 UTC, markkimjr commented on cart/models.py
> +
1. order table에 이미 user_id가 있어서 따로 장바구니에 user_id를 넣지 않았습니다.
2. 최상위 카테고리를 삭제 했을때 하위 카테고리들이 삭제되면 안된다고 생각을 했었는데, 생각해보니 카테고리를 변경할때는 미리 옮겨두는 방법이 있고, 아예 상위카테고리를 삭제하는 경우에는 굳이 데이터를 남길 필요가 없다는걸 알고 다 변경하였습니다~~

2021-02-18 01:56 UTC, markkimjr commented on cart/models.py
> +    billing_last_name           = models.CharField(max_length=45)
전부 100으로 수정했습니다~~

2021-02-18 01:57 UTC, markkimjr commented on product/models.py
> +
추가했습니다~~

2021-02-18 01:57 UTC, markkimjr commented on product/models.py
> +    video    = models.URLField()
max_length 지정하였습니다~~

2021-02-18 01:58 UTC, markkimjr commented on product/models.py
> +    image_url = models.URLField()
max_length 지정하였습니다~~

2021-02-18 02:00 UTC, markkimjr commented on product/models.py
> +    bag_model    = models.ForeignKey('BagModel', on_delete=models.SET_NULL, null=True, related_name='products')
on_delete값을 SET_NULL에서 CASCADE로 변경하여, null=true해제하였습니다~~

2021-02-18 02:00 UTC, markkimjr commented on product/models.py
> +    color_name    = models.CharField(max_length=45)
수정하였습니다~~

2021-02-18 02:00 UTC, markkimjr commented on product/models.py
> +    size_name    = models.CharField(max_length=45)
리뷰사항 전부 반영하여 수정하였습니다! 리뷰 감사합니다~

2021-02-18 05:48 UTC, Kang-kyunghun commented on voucher/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2)
good~!!!

2021-02-18 05:49 UTC, Kang-kyunghun commented on cart/models.py
> +
cart table은 저랑 얘기 한 번 더 해 볼게요~

2021-02-18 06:38 UTC, Kang-kyunghun commented
LGTM!!

2021-02-18 06:39 UTC, Kang-kyunghun approved these changes

2021-02-18 06:40 UTC, merged