MODIFY : cart/views.py (UserCartView)
wecode-bootcamp-korea/17-1st-Dienstag-backend pull request #5
Opened 2021-02-20 06:58 UTC by markkimjr

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- cart/views.py 작성
		 
## 수정 사항들 자세한 내용
- UserCartView class 추가
- OrderStatus 테이블에 name value 두개만 있을 예정이에요 (id=1, name='checking_out'; id=2, name='complete')

## 기타 질문 및 특이 사항
- 아직 login_decorator는 구현 못했는데 미리 써놨어요~

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-21 10:52 UTC, Kang-kyunghun requested changes
전체적인 로직 부분에 대해서 월요일에 미팅 한 번 가지겠습니다.

2021-02-21 10:52 UTC, Kang-kyunghun commented on cart/views.py
> +
불필요한 공백과 주석은 지워주세요.

2021-02-21 10:52 UTC, Kang-kyunghun commented on cart/models.py
> +    voucher = models.ForeignKey('voucher.Voucher', on_delete=models.CASCADE, related_name='carts', null=True)
null = True가 다시 추가된 이유가 있을까요?

2021-02-21 10:52 UTC, Kang-kyunghun commented on db_uploader.py
> +#         Recommendation.objects.create(product_id=row[0], bag_model_id=row[1])
db_uploader 파일도 gitignore에 추가해 주세요.

2021-02-21 10:52 UTC, Kang-kyunghun commented on cart/views.py
> +
불필요한 공백은 제거해 주세요.

2021-02-21 10:52 UTC, Kang-kyunghun commented on cart/views.py
> +class UserCartDetailView(View):
cart 등록과 삭제는 한 view에서 구현 가능 할 것 같습니다. 
같은 자원에 대해 http method에 따라 CRUD를 구현 할 수 있습니다.

2021-02-23 02:13 UTC, markkimjr commented on db_uploader.py
> +#         Recommendation.objects.create(product_id=row[0], bag_model_id=row[1])
넵 추가했습니다!

2021-02-23 02:14 UTC, markkimjr commented on cart/models.py
> +    voucher = models.ForeignKey('voucher.Voucher', on_delete=models.CASCADE, related_name='carts', null=True)
Cart안에 voucher, product 둘중에 하나만 들어갈수 있어서 null=True 추가했어요~

2021-02-23 02:14 UTC, markkimjr commented on cart/views.py
> +
제거했습니다!

2021-02-23 02:16 UTC, markkimjr commented on cart/views.py
> +class UserCartDetailView(View):
Product랑 Voucher 쪼갰어요~ (UserCartProductView, UserCartVoucherView). 피드백 감사합니다!!

2021-02-23 02:44 UTC, markkimjr commented
cart/views.py에서 class이름 "User" 제거했습니다~~

2021-02-23 03:17 UTC, markkimjr commented
order_status_id 하드코딩문제 해결했습니다~ (id안쓰고 name="checking_out"으로 봐꿨어요)

2021-02-23 06:49 UTC, markkimjr commented
한번 더 commit했어요ㅠ Freitag는 product가 하나씩 밖에 없어서 만약에 똑같은 product를 추가하려고하면 에러가 나게끔 CartProductView에 로직 추가했어요~

2021-02-23 17:19 UTC, Kang-kyunghun requested changes

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +
간격은 한 칸으로 해주세요.
위의 import하는 부분도 한 칸으로 해주세요.

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +            if Order.objects.filter(user_id=user_id, order_status__name=ORDER_STATUS_CHECK).exists() and not Cart.objects.filter(product_id=product_id, order__order_status__name=ORDER_STATUS_CHECK, o
if Order.objects.filter(user_id=user_id, order_status__name=ORDER_STATUS_CHECK).exists()
=> order에 order_status가 chacking_out 
위의 조건 너무 잘 만드셨습니다.
저희 원하는 조건은 로그인 한 유저의 order 상태가 checking_out이고(위의 조건) 그 때 연결된 cart에 product_id가 없을 때 인데, 이미 맨 처음 if에서 product_id가 있는 조건을 지나쳐 왔기 때문에 and 이후의 조건은 필요 없을 것 같습니다.
그런데 이것은 어디까지나 생각일 뿐입니다. 실제 shell에서 어떻게 나오는지 확인해 볼 필요가 있습니다.
```suggestion
            if Order.objects.filter(user_id=user_id, order_status__name=ORDER_STATUS_CHECK).exists():
```

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +            if not Order.objects.filter(user_id=user_id, order_status__name=ORDER_STATUS_CHECK).exists():
첫번째 if와 두번째 if을 통해 order_status가 checking_out 상태를 확인 한 상태이므로 마지막 if에서는 무조건  주문완료 상태일 것으로 보입니다. 따라서 if문은 필요하지 않을 것으로 보입니다.
```suggestion
```

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +                        )
Order.objects.create을 order라는 변수에 담으면 생성과 동시에 해당 객체를 바로 사용 할 수 있습니다.
```suggestion
                order = Order.objects.create(
                        user_id         = user_id,
                        order_status_id = OrderStatus.objects.get(name=ORDER_STATUS_CHECK).id
                        )

                Cart.objects.create(
                        product_id = product_id,
                        order_id   = order.id
                        )
```

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +
로직 flow는 너무 잘 하셨습니다.
대신 list comprehension 사용하면 일반 for문 보다 속도 빨라지고, 조금 더 간결한 코드가 나올 것 같습니다.
제가 10층에 올라가기 전까지 한 번 어떻게 할 수 있을지 생각해 보세요~

2021-02-23 17:19 UTC, Kang-kyunghun commented on cart/views.py
> +                    cart.delete()
위의 get 부분을 정리하고 나면 이 부분은 product나 voucher에 상관 없이 구현 할 수 있습니다.

2021-02-24 17:01 UTC, Kang-kyunghun requested changes

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +                return JsonResponse({'message': False}, status=403)
message를 False 말고 장바구니에 이미 제품이 있다는 것을 간단하게 표현 할 수 있는 것으로 바꾸면 좋을 것 같습니다.

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +
objects.get()으로 db에서 데이터를 가져오려면 조건에 맞는 데이터가 무조건 하나여야 합니다.
만약 조건에 맞는 데이터가 0개 또는 2개 이상일 때 어떤 에러가 날 수 있는지 찾아보고 해당 에러에 대해 예외 처리 추가해 주세요.

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +
object.get()에 대한 예외 처리 추가해 주세요.

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +                    }}, status=200)
object.get()에 대한 예외 처리 추가해 주세요.

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +                'image_url'    : cart.product.images.all()[0].image_url if not cart.voucher else None
.all()로 전체를 가져온 뒤에 [0]을 붙여서 첫번째 데이터만 사용하는 이유가 무엇인가요?(질문)

2021-02-24 17:01 UTC, Kang-kyunghun commented on cart/views.py
> +class CartVoucherView(View):
voucher는 product_id처럼 id를 따로 받지 않은 이유가 있을까요? voucher_id를 받게 되면 CartProductView처럼 조금 더 코드가 좋아 질 것 같습니다.

2021-02-25 07:41 UTC, merged