[17기 허정윤] Add: 회원가입 엔드포인트, 로그인 엔드포인트, 로그인 데코레이터 추가
wecode-bootcamp-korea/17-1st-Dienstag-backend pull request #6
Opened 2021-02-21 00:12 UTC by banana1019

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트, 로그인 엔드포인트, 로그인 데코레이터 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- user/views.py: 회원가입 엔드포인트 구현
- user/views.py: 로그인 엔드포인트 구현
- user/utils.py: login decorator 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-21 10:43 UTC, Kang-kyunghun requested changes

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/views.py
> +from django.views import View
import 라인 맞춰 주세요~

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/views.py
> +            user = User.objects.get(email=email)
return 다음에 한 줄 띄어 주세요.

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/views.py
> +            return JsonResponse({'message': 'INVALID_USER'}, status=401)
email이 틀렸을 때랑, 비밀번호가 틀렸을 때 return 메세지를 구분하면 좋을 것 같습니다.
예) INVALID_USER_EMAIL 
지금도 충분할 수 있지만, 나중에 에러가 발생 했을 때를 대비해 어느 부분에서 에러가 나는지 명확히 할 수 있고, 프론트엔드 입장에서 email이 틀렸는지, 비밀번호가 틀렸는지 구분하고 싶을 때도 효과적일 수 있습니다.

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.user_information.get(user=user).password.encode('utf-8')):
#
```suggestion
            if bcrypt.checkpw(password.encode('utf-8'), user.user_information.password.encode('utf-8')):
```
user는 이미 위에서 email을 이용해 특정 user를 선택 했습니다. 따라서 get을 통해 다시 한 번 user를 선택할 필요는 없습니다.

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/views.py
> +
비회원으로 결제 할 때 email 등록하는 로직을 전체적으로 수정할 필요가 있어 보입니다.
순수한 회원 가입 view와 비회원 결제를 위해 등록하는 view을 나눠서 작성하면 좋을 것 같습니다.

2021-02-21 10:43 UTC, Kang-kyunghun commented on user/utils.py
> +            request.user = login_user
```suggestion
            access_token = request.headers['Authorization']
            payload      = jwt.decode(access_token, SECRET, ALGORITHM)
            login_user   = User.objects.get(id=payload['user_id'])
            request.user = login_user
```
위코드 코드 컨벤션 지켜주세요~
다른 부분들도 한 번 더 확인해 주세요

2021-02-21 13:36 UTC, banana1019 commented on user/views.py
> +from django.views import View
수정했습니다~~

2021-02-21 13:37 UTC, banana1019 commented on user/views.py
> +            user = User.objects.get(email=email)
수정했습니다~~!

2021-02-21 13:37 UTC, banana1019 commented on user/views.py
> +            return JsonResponse({'message': 'INVALID_USER'}, status=401)
email과 password 에러 메시지 구분하였습니다~~!

2021-02-21 13:38 UTC, banana1019 commented on user/views.py
> +            if bcrypt.checkpw(password.encode('utf-8'), user.user_information.get(user=user).password.encode('utf-8')):
get을 지우고 values로 변경하였습니다~~

2021-02-21 13:39 UTC, banana1019 commented on user/views.py
> +
내일 팀원들이랑 상의해보고 작성하도록 하겠습니다~~

2021-02-21 13:39 UTC, banana1019 commented on user/utils.py
> +            request.user = login_user
위코드 코드 컨벤션 반영했습니다~~!

2021-02-22 16:16 UTC, Kang-kyunghun requested changes

2021-02-22 16:16 UTC, Kang-kyunghun commented on user/urls.py
> +from user.views import SignUpView, SignInView
import 라인 맞춰 주세요.

2021-02-23 01:41 UTC, banana1019 commented on user/urls.py
> +from user.views import SignUpView, SignInView
수정했습니다~~

2021-02-23 12:06 UTC, Kang-kyunghun commented
고생하셨습니다.!!

2021-02-23 12:06 UTC, merged