ADD: product/views.py | Modify: product/models.py
wecode-bootcamp-korea/17-1st-Dienstag-backend pull request #7
Opened 2021-02-21 16:40 UTC by jaeyiahn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 리스트 페이지 구현하였습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- BackpackListView : backpack 카테고리 상품 리스트들을 보여주는 뷰
- ModelListView : 상세정보와 추천상품테이블을 포함한 모델 리스트를 보여주는 뷰
- 페이지 구성 상 video는 안쓰기로해서 BagModel 테이블의 video column 삭제하였습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-21 16:56 UTC, Kang-kyunghun requested changes

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +from .models import BagType, BagModel, Product, Color, Size, Image, Recommendation
import 라인 맞춰 주세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +        jonanza_items = Product.objects.filter(bag_model=2)
bag_model의 1번과 2번으로 hard coding 하셨는데, 지금은 몇 번이 어떤 제품인줄 알 수 있지만, 다른 사람이 코드를 봤을 때나, 제품의 수가 많아지면 알기 어렵습니다. 
어떻게 하면 hard coding 없이 짤 수 있을까 생각해 보면 좋을 것 같습니다.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +                'image_url' : Image.objects.get(product=product.id).image_url
product가 이미 image와 연결 되어 있기 때문에 Image.objects를 통하지 않고, image에 대한 정보를 가져 올 수 있습니다.
shell에서 어떻게 가져 올 수 있을까 연습해 보세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +                'image_url' : Image.objects.get(product=product.id).image_url
product가 이미 image와 연결 되어 있기 때문에 Image.objects를 통하지 않고, image에 대한 정보를 가져 올 수 있습니다.
shell에서 어떻게 가져 올 수 있을까 연습해 보세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +        return JsonResponse({'message': [pury_list, jonanza_list]}, status=200)
응답값으로 message라는 key 값에 제품 항목들을 보내고 있습니다. message라는 key 값보다는 상황에 맞는 key를 보내 주는 것이 좋습니다. 예를 들어 product나 result 같은 key로 결과를 보낼 수 있습니다.
그리고 최종적으로 front에서 받게 될 데이터의 구조도 프론트와 한 번더 상의해 보세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +                'image_url'    : Image.objects.get(product=product.id).image_url,
product가 이미 image와 연결 되어 있기 때문에 Image.objects를 통하지 않고, image에 대한 정보를 가져 올 수 있습니다.
shell에서 어떻게 가져 올 수 있을까 연습해 보세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +                'image_url'  : Image.objects.get(product=item.id).image_url,
product가 이미 image와 연결 되어 있기 때문에 Image.objects를 통하지 않고, image에 대한 정보를 가져 올 수 있습니다.
shell에서 어떻게 가져 올 수 있을까 연습해 보세요.

2021-02-21 16:56 UTC, Kang-kyunghun commented on product/views.py
> +        return JsonResponse({'message': [model_list, recommendation_list]}, status=200)
위의 리뷰 참고해 주세요.

2021-02-24 03:51 UTC, jaeyiahn commented on product/views.py
> +from .models import BagType, BagModel, Product, Color, Size, Image, Recommendation
넵 수정하였습니다

2021-02-24 03:51 UTC, jaeyiahn commented on product/views.py
> +        jonanza_items = Product.objects.filter(bag_model=2)
수정하였습니다! 감사합니다!!!

2021-02-24 03:53 UTC, jaeyiahn commented on product/views.py
> +                'image_url' : Image.objects.get(product=product.id).image_url
Image를 하나씩만 쓰기로해서 models.py 수정하고 관련된부분 도 다 수정하였습니다.

2021-02-24 03:54 UTC, jaeyiahn commented on product/views.py
> +        return JsonResponse({'message': [pury_list, jonanza_list]}, status=200)
상황에 맞는 키값으로 수정하고 데이터 구조도 말씀해주신대로 수정하였습니다~

2021-02-24 03:54 UTC, jaeyiahn commented on product/views.py
> +        return JsonResponse({'message': [model_list, recommendation_list]}, status=200)
위의 리뷰사항 반영하여 새로 PR날렸습니다! 감사합니다!!!

2021-02-24 06:07 UTC, Kang-kyunghun requested changes

2021-02-24 06:07 UTC, Kang-kyunghun commented on product/views.py
> +        recommendations = BagModel.objects.get(id=bag_model_id).recommendations.all()
recommendations도 product를 통해서 가져 올 수 있을 것 같습니다.

2021-02-24 06:07 UTC, Kang-kyunghun commented on product/views.py
> +        ]
product로 recommandation을 가져오면 하나로 합칠 수 있습니다.

2021-02-24 06:07 UTC, Kang-kyunghun commented on product/views.py
> +
keyword로 color나 size 둘 중 하나만 가져올 수 있나요? 2개 동시에 받을 수는 없을까요?

2021-02-24 06:07 UTC, Kang-kyunghun commented on product/views.py
> +                'description' : product.description.split('/')
.split('/')을 사용한 이유가 무엇인가요??(질문)

2021-02-24 10:14 UTC, jaeyiahn commented on product/views.py
> +        recommendations = BagModel.objects.get(id=bag_model_id).recommendations.all()
recommendation에 있는 bag_model_id는 해당 제품의 실제 bag_model_id가 아니라 보여질 페이지를 나누는 기준이기때문에 Recommendation에서 가져오는걸로 수정했습니다!

2021-02-24 10:17 UTC, jaeyiahn commented on product/views.py
> +        ]
recommendation은 위에 설명했습니다! 그리고 민지님과 얘기해봤는데 제품을 누를때마다 디테일을 가져오는걸로수정하는거는 발표전까지는 힘들것같다고 하시는데 이대로 가도 괜찮을까요....

2021-02-24 10:18 UTC, jaeyiahn commented on product/views.py
> +
Q객체사용으로 수정하였습니다~

2021-02-24 10:20 UTC, jaeyiahn commented on product/views.py
> +                'description' : product.description.split('/')
프론트에서 description 항목을 리스트로 보내달라고 하셔서 .split('/')을 사용하였습니다~ 리뷰 감사합니다

2021-02-25 11:39 UTC, merged